### ISSUE TITLE
Create GHC 9.0.2

### ISSUE THREAD

**Issue by mpilgrem** [fpco/alpine-haskell-stack#5]
I have a proposed pull request to move `stack` to GHC 9.0.2 (`lts-19.6`) - https://github.com/commercialhaskell/stack/pull/5736. I think I have got it to a position where all the the CI and tests work on Windows, but the integration tests fail on other operating systems. I think that is because they need a different docker image. Could one be created?

**Comment by psibi** [comment]
If you can send a PR for it, I can publish the image in docerhub for you. You can target this branch for your PR: https://github.com/fpco/alpine-haskell-stack/tree/ghc902

Also, you might want to use latest stable alpine as base image (I think it's 3.15.4, but I could be wrong).

**Comment by mpilgrem** [comment]
I am not able to do that myself - I am a Windows user, and I do not know where I would begin - but I will repeat your kind offer in the `stack` repository - perhaps somebody there will see it and will be able to action it.

**Comment by psibi** [comment]
Do you think we would be needing GHC 9.0.2 anymore since I think we would be moving stack over to GHC 9.2.3 ?

I have pushed the relevant docker images for both GHC 9.2.3 and GHC 9.2.3.

**Comment by mpilgrem** [comment]
I do not think GHC 9.0.2 will be needed now you are moving to GHC 9.2.3. Once a version of `stack` moves to be built with a particular set of dependencies, intermediate sets of dependencies fall away.

**Comment by psibi** [comment]
Closing this issue as we have new images built for stack's purpose.
